# Generated by Django 3.0.7 on 2020-08-22 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0003_auto_20200822_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='thumbnail',
            field=models.ImageField(blank=True, default='https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg', null=True, upload_to=''),
        ),
    ]
